[target.'cfg(target_os = "macos")']
rustflags = ["-C", "link-args=-Wl,-undefined,dynamic_lookup", "-L", "/opt/homebrew/lib"]

[build]
rustflags = ["-C", "link-args=-Wl,-undefined,dynamic_lookup"]
rustc-link-search = ["/opt/homebrew/lib"] 